# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'mindful' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mindful
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'FirebaseUI/Auth'
 
  pod 'VisionLab', git: 'https://github.com/cocoa-ai/VisionLab'
  pod 'AffdexSDK-iOS'

end
